# Setup
title:               Jae-Kyung Cho
tagline:             'Robotics and deep learning engineer'
url:                 https://jackyoung96.github.io
# baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jae-Kyung Cho
  url:               https://jackyoung96.github.io
  email:             jackyoung96@snu.ac.kr

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap 
  - jekyll-feed
  - jekyll-image-size

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y

remote_theme: poole/lanyon

# Explanation
name: 'Jae-Kyung Cho'
description: | 
  Robotics and deep learning engineer<br>
  SK Telecom<br>
  M.S. of Electrical and Computer Engineer, SNU

github:
  repo: https://github.com/jackyoung96

cv: 
  shared: https://drive.google.com/file/d/1Hzfw2cPT2HoPq3ZtdZvxfnPYO_fk-MF3/view?usp=sharing
  download: https://drive.google.com/uc?export=download&id=1Hzfw2cPT2HoPq3ZtdZvxfnPYO_fk-MF3

codes: ./_codes