# Setup
title:               Jackyoung
tagline:             'Autonomous vehicle engineer'
description:         'An autonomous vehicle researcher in SNU ECS.'
url:                 'https://jackyoung96.github.io'
# baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jaekyung Cho
  url:               https://jackyoung96.github.io
  email:             jackyoung96@snu.ac.kr

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap 
  - jekyll-feed
  - jekyll-image-size

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y

remote_theme: poole/lanyon
